### ISSUE TITLE
Mistake in README.md when building Language tools

### ISSUE THREAD

**Issue by Renji3** [dpelle/vim-LanguageTool#10]
There is a mistake in the section about building the language tools yourself.

To do so you have to install "maven" instead of "mvn"

`sudo apt-get install openjdk-8-jdk maven git`
should be the right command instead of:
`sudo apt-get install openjdk-8-jdk mvn git`

**Comment by eater** [comment]
This does not appear to be fixed in the README.md.

**Comment by dpelle** [comment]
Now fixed in README.md.
Thanks and sorry for the belated response.
