### ISSUE TITLE
relationship between this plugin and LanguageTool.nvim?

### ISSUE THREAD

**Issue by jdhao** [dpelle/vim-LanguageTool#23]
I have just noticed that this plugin is *similar* to [LanguageTool.nvim](https://github.com/vigoux/LanguageTool.nvim), and you are also listed one of the contributors to that plugin. 

So what is the relationship between these two plugins? Is LanguageTool.nvim a fork of this plugin? Or else?

**Comment by dpelle** [comment]
I did not know about that plugin. It looks like clone of my vim-LanguageTool plugin, with some additions (e.g. `]]` and `[[` to navigate in a error summary window, support for server instead of command line of LanguageTool) and maybe more (I did not look in details).

**Comment by Maelan** [comment]
@jdhao, the starting point of this fork is apparently the ignored PR #19 by @vigoux. There you’ll find a TODO list which gives a first clue of what the changes are. This looks all good (especially the first two: replace the deprecated XML API with the new JSON API, use LanguageTool in server mode), but it requires NeoVim, hence the fork.

**Comment by jdhao** [comment]
@Maelan Thanks for pointing this out! 👍

**Comment by vigoux** [comment]
Indeed, LanguageTool.nvim is originally a fork on this plugin. After some work on it though it ended up being a near complete rewrite, appart from the README I think, and most of the ideas this plugin has.
Another thing that is worth noting is that LanguageTool.nvim is built to work with neovim only.
