### ISSUE TITLE
Passive voice rule

### ISSUE THREAD

**Issue by xirdneh** [dpelle/vim-LanguageTool#9]
This plugin has done wonders for my writing.
Although I'm trying to see if it has passive voice checks but it seems like it's not working in vim.
According to this page Language Tool *can* identify passive voice: https://community.languagetool.org/rule/show/PASSIVE_VOICE?lang=en&subId=5

I tried the example in that page but I didn't see any errors showing up.
Is there anything I need to do to get passive voice checks?
Thanks.

**Comment by abers** [comment]
Having same issue. Would be helpful to have a list of possible rules and categories as well as a way to confirm which are currently enabled.

**Comment by dpelle** [comment]
I see in `languagetool/languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/grammar.xml` that the rule is turned-off by default:
```
<rulegroup default="off" id="PASSIVE_VOICE" name="Passive voice">
```
(notice the `default="off"`).

The command line version of LanguageTool has the option `-e` to enable rules which are normally off by default. LanguageTool plugin can enable rules by setting this variable (comma separated rule names). So you solve your problem by adding this in your `~/.vimrc`:

```
:let g:languagetool_enable_rules='PASSIVE_VOICE'
```
I just checked. It works.
